import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { tx } from './siteLang';

export interface SectionPDFOptions {
  committeeName?: string;
  sectionTitle: string;
  columns: string[];
  rows: (string | number | null | undefined)[][];
  notes?: string;
}

const NAVY: [number, number, number] = [23, 42, 79];
const ACCENT: [number, number, number] = [22, 163, 74];

export function generateSectionPDF(opts: SectionPDFOptions): jsPDF {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' });
  const W = doc.internal.pageSize.getWidth();
  const margin = 12;

  // Header band
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, W, 22, 'F');
  doc.setFillColor(...ACCENT);
  doc.rect(0, 22, W, 2, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text('JAWHARATHUL ULOOM SUFFA DARS', W / 2, 10, { align: 'center' });
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(opts.committeeName ? `${opts.committeeName} • ${tx('വിദ്യാർത്ഥി അസോസിയേഷൻ', 'Students Association')}` : tx('വിദ്യാർത്ഥി അസോസിയേഷൻ', 'Students Association'), W / 2, 16, { align: 'center' });

  // Title
  let y = 32;
  doc.setTextColor(...NAVY);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.text(opts.sectionTitle, margin, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(110, 110, 110);
  doc.text(`${tx('തയ്യാറാക്കിയത്', 'Generated')}: ${new Date().toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' })}`, margin, y);
  doc.text(`${tx('ആകെ', 'Total')}: ${opts.rows.length}`, W - margin, y, { align: 'right' });
  y += 4;

  // Table
  if (opts.rows.length === 0) {
    doc.setTextColor(150, 150, 150);
    doc.setFontSize(11);
    doc.text(tx('രേഖകൾ ഇല്ല.', 'No records found.'), W / 2, y + 20, { align: 'center' });
  } else {
    autoTable(doc, {
      startY: y + 3,
      head: [opts.columns],
      body: opts.rows.map(r => r.map(v => v == null ? '' : String(v))),
      styles: { fontSize: 9, cellPadding: 2.5, overflow: 'linebreak' },
      headStyles: { fillColor: NAVY, textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [245, 247, 250] },
      margin: { left: margin, right: margin },
    });
  }

  if (opts.notes) {
    const finalY = (doc as any).lastAutoTable?.finalY ?? y + 10;
    doc.setFontSize(8);
    doc.setTextColor(110, 110, 110);
    doc.text(opts.notes, margin, finalY + 6);
  }

  // Footer
  const H = doc.internal.pageSize.getHeight();
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFillColor(...NAVY);
    doc.rect(0, H - 9, W, 9, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.text(tx('JDSA വിദ്യാർത്ഥി പോർട്ടലിൽ നിന്നും', 'Generated by JDSA Students Portal'), W / 2, H - 3.5, { align: 'center' });
    doc.text(`${tx('പേജ്', 'Page')} ${i} / ${pageCount}`, W - margin, H - 3.5, { align: 'right' });
  }

  return doc;
}

export function downloadSectionPDF(doc: jsPDF, filename: string) {
  doc.save(filename.endsWith('.pdf') ? filename : `${filename}.pdf`);
}

export function printSectionPDF(doc: jsPDF) {
  doc.autoPrint();
  const url = doc.output('bloburl');
  window.open(url as any, '_blank');
}
