import jsPDF from 'jspdf';
import { tx } from './siteLang';

export interface RecordField {
  label: string;
  value: string | number | null | undefined;
  multiline?: boolean;
}

export interface RecordPDFData {
  heading: string;
  subheading?: string;
  date?: string;
  fields: RecordField[];
  body?: string;
  footer?: string;
}

const NAVY: [number, number, number] = [23, 42, 79];
const ACCENT: [number, number, number] = [22, 163, 74];
const INK: [number, number, number] = [30, 30, 30];

export function generateRecordPDF(data: RecordPDFData): jsPDF {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  const margin = 15;
  let y = margin;

  // Header band
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, W, 22, 'F');
  doc.setFillColor(...ACCENT);
  doc.rect(0, 22, W, 2, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('JAWHARATHUL ULOOM SUFFA DARS', W / 2, 10, { align: 'center' });
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(tx('വിദ്യാർത്ഥി അസോസിയേഷൻ', 'Students Association'), W / 2, 16, { align: 'center' });

  y = 32;
  doc.setTextColor(...NAVY);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  const headLines = doc.splitTextToSize(data.heading, W - margin * 2);
  doc.text(headLines, margin, y);
  y += headLines.length * 7;

  if (data.subheading) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(data.subheading, margin, y);
    y += 5;
  }
  if (data.date) {
    doc.setFontSize(9);
    doc.setTextColor(...ACCENT);
    doc.text(`${tx('തീയതി', 'Date')}: ${data.date}`, margin, y);
    y += 5;
  }

  // divider
  doc.setDrawColor(...ACCENT);
  doc.setLineWidth(0.4);
  doc.line(margin, y, W - margin, y);
  y += 6;

  // Fields
  doc.setTextColor(...INK);
  doc.setFontSize(11);
  for (const f of data.fields) {
    if (f.value == null || f.value === '') continue;
    if (y > 270) { doc.addPage(); y = margin; }
    doc.setFont('helvetica', 'bold');
    doc.text(`${f.label}:`, margin, y);
    doc.setFont('helvetica', 'normal');
    const text = String(f.value);
    if (f.multiline || text.length > 60) {
      y += 5;
      const lines = doc.splitTextToSize(text, W - margin * 2);
      doc.text(lines, margin, y);
      y += lines.length * 5 + 3;
    } else {
      doc.text(text, margin + 40, y);
      y += 7;
    }
  }

  if (data.body) {
    if (y > 250) { doc.addPage(); y = margin; }
    y += 4;
    doc.setDrawColor(220, 220, 220);
    doc.line(margin, y, W - margin, y);
    y += 6;
    doc.setFont('helvetica', 'bold');
    doc.text(tx('വിശദാംശങ്ങൾ', 'Details'), margin, y);
    y += 6;
    doc.setFont('helvetica', 'normal');
    const bodyLines = doc.splitTextToSize(data.body, W - margin * 2);
    for (const line of bodyLines) {
      if (y > 280) { doc.addPage(); y = margin; }
      doc.text(line, margin, y);
      y += 5;
    }
  }

  // Footer
  const H = doc.internal.pageSize.getHeight();
  doc.setFillColor(...NAVY);
  doc.rect(0, H - 10, W, 10, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.text(data.footer || tx('JDSA വിദ്യാർത്ഥി പോർട്ടലിൽ നിന്നും', 'Generated by JDSA Students Portal'), W / 2, H - 4, { align: 'center' });

  return doc;
}

export function downloadPDF(doc: jsPDF, filename: string) {
  doc.save(filename.endsWith('.pdf') ? filename : `${filename}.pdf`);
}

export function printPDF(doc: jsPDF) {
  doc.autoPrint();
  const url = doc.output('bloburl');
  window.open(url as any, '_blank');
}
